<a href="https://colab.research.google.com/github/RubaAlshamrani/CS392-F22-HW4--Ruba-Alshamrani-/blob/main/Yet_another_copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ASSIGMENT 2

##**lung.mat**

Step 1: Load the Dataset

In [ ]:
# Load pakages and Library for working
from sklearn.model_selection import train_test_split
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB
# import a KNeighbors classifier
from sklearn.neighbors import KNeighborsClassifier
# Test Accuracy
from sklearn.metrics import accuracy_score
# import time module to calc classification time in second
import time
# import the NumPy module
import numpy as np
# import the classification report module
from sklearn.metrics import classification_report





# Load the .mat file
from scipy.io import loadmat
import pandas as pd

lung = loadmat('/content/lung(1).mat')


Step 2: Data Exploration





In [ ]:
X_lung= pd.DataFrame(lung['X'])
Y_lung = pd.DataFrame(lung['Y'])

#Print descriptive analysis about dataset
X_lung.describe()

0           1           2           3           4           5     \
count  203.000000  203.000000  203.000000  203.000000  203.000000  203.000000   
mean     3.852954    1.897285    1.882023    2.456568    3.363554    3.370603   
std      0.046501    0.373249    0.289968    0.226589    0.175697    0.173235   
min      3.719071    1.000000    1.000000    1.794627    2.705282    2.894842   
25%      3.821581    1.659363    1.710455    2.307828    3.265530    3.262582   
50%      3.851614    1.965766    1.897517    2.447375    3.381507    3.389742   
75%      3.884363    2.167347    2.092614    2.606816    3.470232    3.483416   
max      3.972624    2.695455    2.618947    3.001301    3.719680    3.722039   

             6           7           8           9     ...        3302  \
count  203.000000  203.000000  203.000000  203.000000  ...  203.000000   
mean     3.509625    3.474571    3.585993    3.624655  ...    1.707262   
std      0.126212    0.118195    0.092053    0.067111  ...    0.426523   
min      3.032066    2.988260    3.182261    3.313268  ...    1.000000   
25%      3.434958    3.433452    3.549895    3.595060  ...    1.421668   
50%      3.528263    3.494889    3.599013    3.634678  ...    1.803389   
75%      3.596736    3.552158    3.647148    3.673326  ...    2.048031   
max      3.736109    3.688640    3.742079    3.742775  ...    2.409062   

             3303        3304        3305        3306        3307        3308  \
count  203.000000  203.000000  203.000000  203.000000  203.000000  203.000000   
mean     1.750352    1.285979    2.173430    3.089952    1.874063    2.577062   
std      0.266247    0.384384    0.127722    0.207293    0.233210    0.108382   
min      1.000000    1.000000    1.794279    2.541442    1.000000    2.272538   
25%      1.577721    1.000000    2.102742    2.962347    1.758571    2.503154   
50%      1.731105    1.008600    2.162594    3.102663    1.872913    2.584422   
75%      1.877596    1.511749    2.237239    3.254805    2.018471    2.644719   
max      2.625282    2.749102    2.559811    3.526727    2.723685    2.845278   

             3309        3310        3311  
count  203.000000  203.000000  203.000000  
mean     1.586416    2.469248    2.024278  
std      0.537254    0.286999    0.269620  
min      1.000000    1.627263    1.000000  
25%      1.000000    2.296620    1.911400  
50%      1.615055    2.535148    2.084433  
75%      2.049759    2.647993    2.195581  
max      2.903432    3.084301    2.575834  

[8 rows x 3312 columns]

In [ ]:
#Print the number of samples and the number of features
#RangeIndex = samples, Columns = features)
X_lung.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Columns: 3312 entries, 0 to 3311
dtypes: float64(3312)
memory usage: 5.1 MB


In [ ]:
#Print the number of classes
print(Y_lung.value_counts(),Y_lung.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       203 non-null    uint8
dtypes: uint8(1)
memory usage: 331.0 bytes
1    139
3     21
4     20
2     17
5      6
dtype: int64 None


Step 3: Split the Dataset

In [ ]:
#Spilt data 20% testing and 80% training
x_train, x_test, y_train, y_test = train_test_split(X_lung, Y_lung, test_size = 0.2 , random_state = 0)
#(training samples , All data) (testing samples , All data)
print(x_train.shape,x_test.shape)

(162, 3312) (41, 3312)


Step 4: Naïve Bayes Classifier

*a. Train a Naïve Bayes classifier on the training set.italicised text*

In [ ]:
# instantiate the model
GNP = GaussianNB()
# fit the model

GNP.fit(x_train, y_train)
StartTime = time.time()
predictions = GNP.predict(x_test)
EndTime = time.time()
ElapsedTime = EndTime - StartTime
print(f"Elapsed time: {ElapsedTime} seconds")
predictions

Elapsed time: 0.037194013595581055 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1],
      dtype=uint8)

*b. Make predictions on the testing set.*

In [ ]:
#print the accuracy, computation time, average and standard deviation
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")
print("average : ", np.average(predictions))
print("Standard Deviation : ", np.std(predictions))

Accuracy Score : 0.19512195121951215
Elapsed time : 0.037194013595581055 seconds
average :  1.3414634146341464
Standard Deviation :  0.9268292682926829


Step 5: k-NN Classifier

a.Run k-NN classifier for k value = 1

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(1)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy Score : 0.07317073170731703
Elapsed time : 0.037194013595581055 seconds


b.Run k-NN classifier for k value = 3

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(3)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.07317073170731703
Elapsed time : 0.037194013595581055 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


c.Run k-NN classifier for k value = 7

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(7)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.07317073170731703
Elapsed time : 0.037194013595581055 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


##**Isolet.mat file**


Step 1: Load the Dataset

In [ ]:
# Load pakages and Library for working
from sklearn.model_selection import train_test_split
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB
# import a KNeighbors classifier
from sklearn.neighbors import KNeighborsClassifier
# Test Accuracy
from sklearn.metrics import accuracy_score
# import time module to calc classification time in second
import time
# import the NumPy module
import numpy as np
# import the classification report module
from sklearn.metrics import classification_report





# Load the .mat file
from scipy.io import loadmat
import pandas as pd

Isolet = loadmat('/content/Isolet(1).mat')


Step 2: Data Exploration

In [ ]:
x = pd.DataFrame(Isolet['X'])
y = pd.DataFrame(Isolet['Y'])

#Print descriptive analysis about dataset
x.describe()

0            1            2            3            4    \
count  1560.000000  1560.000000  1560.000000  1560.000000  1560.000000   
mean     -0.352255     0.216822     0.381779     0.449188     0.390882   
std       0.268956     0.345982     0.335157     0.320194     0.393687   
min      -1.000000    -0.721600    -0.858800    -0.968000    -0.913400   
25%      -0.532450    -0.031500     0.136600     0.249000     0.176600   
50%      -0.351900     0.174400     0.345400     0.453700     0.456500   
75%      -0.175950     0.452500     0.632800     0.679600     0.692600   
max       0.840000     1.000000     1.000000     1.000000     1.000000   

               5            6            7            8            9    ...  \
count  1560.000000  1560.000000  1560.000000  1560.000000  1560.000000  ...   
mean      0.278666     0.197792     0.088165    -0.005391    -0.076504  ...   
std       0.526396     0.539334     0.503402     0.493222     0.492835  ...   
min      -0.940800    -0.990400    -0.971800    -0.986200    -1.000000  ...   
25%      -0.137150    -0.268750    -0.321500    -0.416450    -0.466700  ...   
50%       0.365000     0.219700     0.065500    -0.037000    -0.108700  ...   
75%       0.736500     0.691000     0.496250     0.341900     0.234100  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

               607          608          609          610          611  \
count  1560.000000  1560.000000  1560.000000  1560.000000  1560.000000   
mean      0.409187     0.362451     0.296515     0.277845     0.285129   
std       0.320851     0.318095     0.329547     0.343738     0.358508   
min      -0.495000    -0.660800    -0.533400    -0.661200    -0.711800   
25%       0.177300     0.122000     0.050450     0.020800     0.017150   
50%       0.406000     0.359200     0.274100     0.250000     0.245100   
75%       0.653600     0.606800     0.541150     0.533500     0.558500   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               612          613          614          615          616  
count  1560.000000  1560.000000  1560.000000  1560.000000  1560.000000  
mean      0.263708     0.207242     0.180301     0.094831    -0.257722  
std       0.353277     0.359532     0.364925     0.352304     0.370798  
min      -0.543800    -0.790600    -0.763600    -0.802800    -0.946000  
25%      -0.009100    -0.056700    -0.086200    -0.149000    -0.531900  
50%       0.232400     0.164400     0.140200     0.051900    -0.315600  
75%       0.521050     0.460250     0.415250     0.321400    -0.049650  
max       1.000000     1.000000     1.000000     1.000000     0.889800  

[8 rows x 617 columns]

In [ ]:
#Print the number of samples and the number of features
#RangeIndex = samples, Columns = features)
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Columns: 617 entries, 0 to 616
dtypes: float64(617)
memory usage: 7.3 MB


In [ ]:
#Print the number of classes
print(y.value_counts(),y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1560 non-null   uint8
dtypes: uint8(1)
memory usage: 1.6 KB
1     60
2     60
25    60
24    60
23    60
22    60
21    60
20    60
19    60
18    60
17    60
16    60
15    60
14    60
13    60
12    60
11    60
10    60
9     60
8     60
7     60
6     60
5     60
4     60
3     60
26    60
dtype: int64 None


Step 3: Split the Dataset

In [ ]:
#Spilt data, the test set should have 20 points
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.091 , random_state = 0)
x_test

#(training samples , All data) (The test set have 20 point , All data)
print(x_train.shape,x_test.shape)

NameError: ignored

Step 4: Naïve Bayes Classifier

a. Train a Naïve Bayes classifier on the training set.

In [ ]:
# instantiate the model
GNP = GaussianNB()
# fit the model

GNP.fit(x_train, y_train)
StartTime = time.time()
predictions = GNP.predict(x_test)
EndTime = time.time()
ElapsedTime = EndTime - StartTime
print(f"Elapsed time: {ElapsedTime} seconds")
predictions

Elapsed time: 0.03190422058105469 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 6, 18, 14, 10,  7,  9, 11, 23, 22,  9,  7, 15,  9, 16,  1, 22,  8,
        2, 22, 25, 11,  5,  6, 12,  1,  3, 18,  6, 19,  8, 25,  1, 26,  1,
       16, 25, 23, 11, 14,  1,  8, 18, 16, 21,  5,  2,  1,  9, 23, 26, 17,
        6, 15, 12, 17, 12, 20,  3,  5, 16, 20, 14,  3,  7,  6, 11, 23, 12,
       23,  4, 10, 12, 17, 17, 23, 14,  6,  3,  9, 18,  4, 20,  5, 25,  5,
       10,  8,  8, 21, 23,  3,  6, 16, 23, 11, 20, 12, 24, 26,  7, 14, 14,
       14, 18,  8, 13, 20,  5,  8, 14,  6, 24,  9, 10, 26,  5, 13, 17, 13,
       21, 24, 20,  9,  5, 25,  5, 15, 17, 20, 25, 16, 12,  1, 18, 22, 23,
       17, 18, 17,  7,  5, 23, 11, 23, 23,  6,  5, 20, 15, 19, 20,  6, 25,
       14,  8, 19,  2, 20, 21,  7,  2,  5, 16, 23, 20, 23, 12,  3,  2,  4,
        8, 26, 19,  4, 10,  3,  9, 19,  9, 20, 21, 20,  6,  3, 11, 24, 12,
        1,  5,  6, 22, 23, 12, 22,  8,  6, 20, 16,  9, 24, 17, 20, 24, 26,
       20, 11, 14,  1,  5,  6, 10, 19, 21, 19, 20, 25,  6, 20, 20,  6, 11,
       12, 17, 20, 23,  3

b. Make predictions on the testing set.

In [ ]:
#print the accuracy, computation time, average and standard deviation
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")
print("average : ", np.average(predictions))
print("Standard Deviation : ", np.std(predictions))

Accuracy Score : 0.19551282051282048
Elapsed time : 0.03190422058105469 seconds
average :  13.08974358974359
Standard Deviation :  7.573462266591453


Step 5: k-NN Classifier

a.Run k-NN classifier for k value = 1

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(1)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy Score : 0.1282051282051282
Elapsed time : 0.03190422058105469 seconds


b.Run k-NN classifier for k value = 3

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(3)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.14743589743589747
Elapsed time : 0.03190422058105469 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


c.Run k-NN classifier for k value = 7

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(7)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.1314102564102564
Elapsed time : 0.03190422058105469 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


##**USPS.mat file**


Step 1: Load the Dataset

In [ ]:
# Load pakages and Library for working
from sklearn.model_selection import train_test_split
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB
# import a KNeighbors classifier
from sklearn.neighbors import KNeighborsClassifier
# Test Accuracy
from sklearn.metrics import accuracy_score
# import time module to calc classification time in second
import time
# import the NumPy module
import numpy as np
# import the classification report module
from sklearn.metrics import classification_report





# Load the .mat file
from scipy.io import loadmat
import pandas as pd

USPS = loadmat('/content/USPS(1).mat')


Step 2: Data Exploration





In [ ]:
X_USPS= pd.DataFrame(USPS['X'])
Y_USPS = pd.DataFrame(USPS['Y'])

#Print descriptive analysis about dataset
X_USPS.describe()

0            1            2            3            4    \
count  9298.000000  9298.000000  9298.000000  9298.000000  9298.000000   
mean     -0.991800    -0.972226    -0.930421    -0.852805    -0.733673   
std       0.050814     0.118296     0.195285     0.284053     0.372653   
min      -1.000000    -1.000000    -1.000000    -1.000000    -1.000000   
25%      -1.000000    -1.000000    -1.000000    -0.999914    -0.996085   
50%      -1.000000    -0.999992    -0.999609    -0.991661    -0.932991   
75%      -0.999969    -0.998444    -0.979572    -0.861493    -0.589829   
max       0.000308     0.332928     0.479436     0.523534     0.527370   

               5            6            7            8            9    ...  \
count  9298.000000  9298.000000  9298.000000  9298.000000  9298.000000  ...   
mean     -0.578239    -0.391187    -0.228260    -0.220399    -0.354626  ...   
std       0.435317     0.452878     0.454537     0.446069     0.454492  ...   
min      -1.000000    -1.000000    -1.000000    -1.000000    -1.000000  ...   
25%      -0.963110    -0.787003    -0.620084    -0.571667    -0.776483  ...   
50%      -0.747495    -0.447742    -0.138583    -0.147614    -0.378182  ...   
75%      -0.260331     0.000547     0.143727     0.148815     0.047713  ...   
max       0.531509     0.531319     0.531368     0.531327     0.531257  ...   

               246          247          248          249          250  \
count  9298.000000  9298.000000  9298.000000  9298.000000  9298.000000   
mean     -0.292865    -0.118513    -0.138364    -0.357547    -0.595574   
std       0.483898     0.453286     0.449512     0.456625     0.422421   
min      -1.000000    -1.000000    -1.000000    -1.000000    -1.000000   
25%      -0.742622    -0.430494    -0.465960    -0.770638    -0.968696   
50%      -0.283600    -0.022176    -0.039908    -0.392889    -0.755935   
75%       0.153226     0.251788     0.220543     0.033934    -0.306862   
max       0.531380     0.531834     0.531857     0.531830     0.531472   

               251          252          253          254          255  
count  9298.000000  9298.000000  9298.000000  9298.000000  9298.000000  
mean     -0.766226    -0.874332    -0.936784    -0.970873    -0.989597  
std       0.340464     0.254392     0.183444     0.120247     0.058028  
min      -1.000000    -1.000000    -1.000000    -1.000000    -1.000000  
25%      -0.997447    -0.999957    -1.000000    -1.000000    -1.000000  
50%      -0.946958    -0.993475    -0.999771    -0.999996    -1.000000  
75%      -0.654382    -0.885085    -0.979766    -0.998040    -0.999942  
max       0.523678     0.524670     0.470479     0.314115    -0.162598  

[8 rows x 256 columns]

In [ ]:
#Print the number of samples and the number of features
#RangeIndex = samples, Columns = features)
X_USPS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9298 entries, 0 to 9297
Columns: 256 entries, 0 to 255
dtypes: float64(256)
memory usage: 18.2 MB


In [ ]:
#Print the number of classes
print(Y_USPS.value_counts(),Y_USPS.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9298 entries, 0 to 9297
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       9298 non-null   uint8
dtypes: uint8(1)
memory usage: 9.2 KB
1     1553
2     1269
3      929
5      852
7      834
4      824
10     821
8      792
6      716
9      708
dtype: int64 None


Step 3: Split the Dataset

In [ ]:
#Spilt data 20% testing and 80% training
x_train, x_test, y_train, y_test = train_test_split(X_USPS, Y_USPS, test_size = 0.2 , random_state = 0)
#(training samples , All data) (testing samples , All data)
print(x_train.shape,x_test.shape)

(8451, 256) (847, 256)


Step 4: Naïve Bayes Classifier

*a. Train a Naïve Bayes classifier on the training set.italicised text*

In [ ]:
# instantiate the model
GNP = GaussianNB()
# fit the model

GNP.fit(x_train, y_train)
StartTime = time.time()
predictions = GNP.predict(x_test)
EndTime = time.time()
ElapsedTime = EndTime - StartTime
print(f"Elapsed time: {ElapsedTime} seconds")
predictions

Elapsed time: 0.018651485443115234 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 8, 3, ..., 3, 4, 8], dtype=uint8)

*b. Make predictions on the testing set.*

In [ ]:
#print the accuracy, computation time, average and standard deviation
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")
print("average : ", np.average(predictions))
print("Standard Deviation : ", np.std(predictions))

Accuracy Score : 0.2182795698924731
Elapsed time : 0.018651485443115234 seconds
average :  5.327419354838709
Standard Deviation :  3.2453110602691013


Step 5: k-NN Classifier

a.Run k-NN classifier for k value = 1

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(1)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy Score : 0.025268817204301075
Elapsed time : 0.018651485443115234 seconds


b.Run k-NN classifier for k value = 3

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(3)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy Score : 0.0317204301075269
Elapsed time : 0.018651485443115234 seconds


c.Run k-NN classifier for k value = 7

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(7)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy Score : 0.03655913978494618
Elapsed time : 0.018651485443115234 seconds


##**COIL20.mat file**


Step 1: Load the Dataset

In [ ]:
# Load pakages and Library for working
from sklearn.model_selection import train_test_split
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB
# import a KNeighbors classifier
from sklearn.neighbors import KNeighborsClassifier
# Test Accuracy
from sklearn.metrics import accuracy_score
# import time module to calc classification time in second
import time
# import the NumPy module
import numpy as np
# import the classification report module
from sklearn.metrics import classification_report





# Load the .mat file
from scipy.io import loadmat
import pandas as pd

COIL20 = loadmat('/content/COIL20.mat')


Step 2: Data Exploration

In [ ]:
x = pd.DataFrame(COIL20['X'])
y = pd.DataFrame(COIL20['Y'])

#Print descriptive analysis about dataset
x.describe()

[[0.01568627 0.01568627 0.01568627 ... 0.01568627 0.01568627 0.01568627]
 [0.01960784 0.01960784 0.01960784 ... 0.01960784 0.01960784 0.01960784]
 [0.01568627 0.01568627 0.01568627 ... 0.01568627 0.01568627 0.01568627]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[ 1  1  1 ... 20 20 20]


In [ ]:
#Print the number of samples and the number of features
#RangeIndex = samples, Columns = features)
x.info()

In [ ]:
#Print the number of classes
print(y.value_counts(),y.info())

Step 3: Split the Dataset

In [ ]:
#Spilt data 20% testing and 80% training
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2 , random_state = 0)
#(training samples , All data) (testing samples , All data)
print(x_train.shape,x_test.shape)

Step 4: Naïve Bayes Classifier

a. Train a Naïve Bayes classifier on the training set.

In [ ]:
# instantiate the model
GNP = GaussianNB()
# fit the model

GNP.fit(x_train, y_train)
StartTime = time.time()
predictions = GNP.predict(x_test)
EndTime = time.time()
ElapsedTime = EndTime - StartTime
print(f"Elapsed time: {ElapsedTime} seconds")
predictions

b. Make predictions on the testing set.

In [ ]:
#print the accuracy, computation time, average and standard deviation
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")
print("average : ", np.average(predictions))
print("Standard Deviation : ", np.std(predictions))

Step 5: k-NN Classifier

a.Run k-NN classifier for k value = 1

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(1)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

b.Run k-NN classifier for k value = 3

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(3)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Naïve Bayes Classifier:
Classification Time: 0.01 seconds
Classification Accuracy: 0.91
Error Rate: 0.09

k-NN Classifier:
k = 1
Classification Time: 0.00 seconds
Classification Accuracy: 1.00

k = 3
Classification Time: 0.00 seconds
Classification Accuracy: 1.00

k = 7
Classification Time: 0.00 seconds
Classification Accuracy: 0.94



c.Run k-NN classifier for k value = 7

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(7)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

##**warpPIE10P.mat file**


Step 1: Load the Dataset

In [ ]:
# Load pakages and Library for working
from sklearn.model_selection import train_test_split
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB
# import a KNeighbors classifier
from sklearn.neighbors import KNeighborsClassifier
# Test Accuracy
from sklearn.metrics import accuracy_score
# import time module to calc classification time in second
import time
# import the NumPy module
import numpy as np
# import the classification report module
from sklearn.metrics import classification_report





# Load the .mat file
from scipy.io import loadmat
import pandas as pd

warpPIE10P = loadmat('/content/warpPIE10P.mat')


Step 2: Data Exploration

In [ ]:
x = pd.DataFrame(warpPIE10P['X'])
y = pd.DataFrame(warpPIE10P['Y'])

#Print descriptive analysis about dataset
x.describe()

0           1           2           3           4           5     \
count  210.000000  210.000000  210.000000  210.000000  210.000000  210.000000   
mean    11.147619   13.047619   12.338095   12.909524   13.576190   14.533333   
std     14.359770   21.208187   16.321090   13.755083   12.474525   15.433182   
min      1.000000    3.000000    1.000000    3.000000    1.000000    2.000000   
25%      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   
50%      7.000000    8.000000    7.000000    8.000000    9.000000    9.000000   
75%     10.000000   11.000000   12.000000   13.000000   16.000000   15.000000   
max    105.000000  230.000000  135.000000  103.000000   72.000000  100.000000   

             6           7           8           9     ...        2410  \
count  210.000000  210.000000  210.000000  210.000000  ...  210.000000   
mean    13.461905   13.180952   15.266667   17.252381  ...   51.242857   
std     11.821276   11.340136   15.261840   16.328509  ...   41.979638   
min      2.000000    3.000000    1.000000    3.000000  ...    4.000000   
25%      5.000000    5.000000    5.000000    6.000000  ...   25.000000   
50%      9.000000    8.000000    9.000000   10.000000  ...   40.000000   
75%     18.000000   16.000000   19.750000   22.000000  ...   65.000000   
max     88.000000   66.000000   77.000000   77.000000  ...  248.000000   

             2411        2412        2413        2414        2415        2416  \
count  210.000000  210.000000  210.000000  210.000000  210.000000  210.000000   
mean    49.709524   51.961905   55.823810   56.371429   51.947619   53.704762   
std     40.993364   40.877439   40.725507   42.528517   41.428004   39.981556   
min      5.000000    6.000000    6.000000    3.000000    3.000000    6.000000   
25%     24.250000   28.000000   28.000000   27.000000   26.250000   28.000000   
50%     39.000000   40.000000   47.000000   44.000000   38.000000   41.000000   
75%     59.000000   61.750000   72.000000   76.000000   63.000000   65.750000   
max    248.000000  234.000000  235.000000  233.000000  228.000000  233.000000   

             2417        2418        2419  
count  210.000000  210.000000  210.000000  
mean    52.385714   57.042857   58.195238  
std     41.098537   43.596267   44.684379  
min      3.000000    3.000000    3.000000  
25%     25.000000   18.250000   19.000000  
50%     41.500000   48.500000   48.500000  
75%     73.000000   91.500000   89.750000  
max    222.000000  214.000000  209.000000  

[8 rows x 2420 columns]

<Figure size 600x480 with 0 Axes>

In [ ]:
#Print the number of samples and the number of features
#RangeIndex = samples, Columns = features)
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Columns: 2420 entries, 0 to 2419
dtypes: uint8(2420)
memory usage: 496.4 KB


In [ ]:
#Print the number of classes
print(y.value_counts(),y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       210 non-null    uint8
dtypes: uint8(1)
memory usage: 338.0 bytes
1     21
2     21
3     21
4     21
5     21
6     21
7     21
8     21
9     21
10    21
dtype: int64 None


Step 3: Split the Dataset

In [ ]:
#Spilt data, the test set should have 20 points
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.091 , random_state = 0)
x_test

#(training samples , All data) (The test set have 20 point , All data)
print(x_train.shape,x_test.shape)


(190, 2420) (20, 2420)


Step 4: Naïve Bayes Classifier

a. Train a Naïve Bayes classifier on the training set.

In [ ]:
# instantiate the model
GNP = GaussianNB()
# fit the model

GNP.fit(x_train, y_train)
StartTime = time.time()
predictions = GNP.predict(x_test)
EndTime = time.time()
ElapsedTime = EndTime - StartTime
print(f"Elapsed time: {ElapsedTime} seconds")
predictions

Elapsed time: 0.03019094467163086 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 1,  4,  2,  1,  3,  4,  6,  6,  5,  8,  3,  8,  3, 10,  5,  5, 10,
        2,  4,  1], dtype=uint8)

b. Make predictions on the testing set.

In [ ]:
#print the accuracy, computation time, average and standard deviation
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")
print("average : ", np.average(predictions))
print("Standard Deviation : ", np.std(predictions))

Accuracy Score : 0.050000000000000044
Elapsed time : 0.03019094467163086 seconds
average :  4.55
Standard Deviation :  2.71062723368596


Step 5: k-NN Classifier

a.Run k-NN classifier for k value = 1

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(1)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.0
Elapsed time : 0.03019094467163086 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


b.Run k-NN classifier for k value = 3

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(3)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.0
Elapsed time : 0.03019094467163086 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


c.Run k-NN classifier for k value = 7

In [ ]:
# instantiate the model
knn = KNeighborsClassifier(7)
# fit the model
knn.fit(x_train, y_train)
StartTime = time.time()
predictions = knn.predict(x_test)
EndTime = time.time()
elapsed_time = EndTime - StartTime

#print the accuracy and computation time
print("Accuracy Score :", 1 - accuracy_score(predictions, y_test))
print(f"Elapsed time : {ElapsedTime} seconds")

Accuracy Score : 0.050000000000000044
Elapsed time : 0.03019094467163086 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
